# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genD_cpp <- function(h0, func, x, d, r, v, eps, zero_tol) {
    .Call('_RcppnumDeriv_genD_cpp', PACKAGE = 'RcppnumDeriv', h0, func, x, d, r, v, eps, zero_tol)
}

